# Generated by Django 4.1.7 on 2023-03-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_alter_curso_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telefono', models.CharField(blank=True, max_length=256, null=True)),
                ('genero', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
