# Generated by Django 4.1.7 on 2023-03-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
